name: pushDocs

on:
  push:
    branches: 
     - master


jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

     # 具体的执行步骤
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - name: Checkout
        uses: actions/checkout@master

      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@master
        with:
          node-version:  15.0.0
      
      - name: Install dependencies
        run: npm install
    
      - name: Build VuePress
        run: npm run build
        
      - name: Build and Deploy
        uses: theme-keep/hexo-deploy-github-pages-action@master
        env:
          PERSONAL_TOKEN: ${{ secrets.ACCESS_TOKEN }}
          PUBLISH_REPOSITORY: kfhechenglong/blog
          BRANCH: gh-pages
          PUBLISH_DIR: ./public
          
      # - name: Deploy
      #   uses: easingthemes/ssh-deploy@v2.1.5
      #   env:
      #     # 密匙
      #     SSH_PRIVATE_KEY: ${{ secrets.SERVER_SSH_KEY }}
      #     ARGS: '-rltgoDzvO --delete'
      #     SOURCE: "public/ " # 将要复制到云服务器的静态文件夹
      #     REMOTE_HOST: ${{ secrets.SERVER_SSH_HOST }} # 云服务器公网地址
      #     REMOTE_USER: "root" # 服务器用户名
      #     TARGET: ${{ secrets.SERVER_SSH_TARGET }} # 打包后的文件夹将放在目录

